version: '3.5'

services:
  quiz-app:
    build:
      context: frontend
    volumes:
      - './frontend:/app'
    ports:
      - '3000:3000'

  api:
    build:
      context: backend
    volumes:
      - './backend:/app/'
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'